# Generated by Django 3.0 on 2022-06-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('Profile', 'profiles_Profile')
    ]

    state_operations = [
        migrations.DeleteModel('Profile')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
