# Generated by Django 3.0 on 2022-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220610_1512'),
    ]

    database_operations = [
        migrations.AlterModelTable('Address', 'lettings_Address'),
        migrations.AlterModelTable('Letting', 'lettings_Letting'),
    ]

    state_operations = [
        migrations.DeleteModel('Address'),
        migrations.DeleteModel('Letting'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
